# Generated by Django 5.2.1 on 2025-05-17 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pwebapp', '0002_order_closed_at_order_opened_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pwebapp.person'),
        ),
    ]
